-- ============================================================
-- Guest List Table
-- Run this in the Supabase SQL Editor
-- ============================================================

CREATE TABLE IF NOT EXISTS guest_items (
  id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  first_name text NOT NULL DEFAULT '',
  last_name text NOT NULL DEFAULT '',
  side text NOT NULL DEFAULT 'groom' CHECK (side IN ('bride', 'groom')),
  rsvp_status text NOT NULL DEFAULT 'pending' CHECK (rsvp_status IN ('pending', 'confirmed', 'declined')),
  meal_preference text NOT NULL DEFAULT '',
  save_the_date_sent boolean NOT NULL DEFAULT false,
  invitation_sent boolean NOT NULL DEFAULT false,
  category text NOT NULL DEFAULT '',
  count integer NOT NULL DEFAULT 1,
  address text NOT NULL DEFAULT '',
  gifted_amount numeric NOT NULL DEFAULT 0,
  created_at timestamptz DEFAULT now()
);

ALTER TABLE guest_items ENABLE ROW LEVEL SECURITY;
CREATE POLICY "allow_all_guest_items" ON guest_items FOR ALL USING (true) WITH CHECK (true);

-- ============================================================
-- Seed Data — Amaya's Guest List (Bride's Side)
-- ============================================================

INSERT INTO guest_items (first_name, last_name, side, category, address, gifted_amount, count, rsvp_status, save_the_date_sent, invitation_sent, meal_preference) VALUES
('Heshan', 'Perera', 'bride', 'Family', 'Moratuwa', 0, 3, 'pending', false, false, ''),
('Oliver', 'Fernando', 'bride', '', 'Moratuwa', 0, 2, 'pending', false, false, ''),
('Ayoma', 'Perera', 'bride', '', 'Moratuwa', 0, 1, 'pending', false, false, ''),
('Violet', 'Fernando', 'bride', '', 'Moratuwa', 0, 1, 'pending', false, false, ''),
('Praveen', 'Perera', 'bride', '', 'Moratuwa', 0, 4, 'pending', false, false, ''),
('Jude', 'De Sayrah', 'bride', '', 'Moratuwa', 0, 4, 'pending', false, false, ''),
('Shanake', 'Fernando', 'bride', '', 'Korea', 0, 1, 'pending', false, false, ''),
('Anthony', 'Fernando', 'bride', '', 'Australia', 0, 3, 'pending', false, false, ''),
('Nuwan', 'Fernando', 'bride', '', 'Australia', 0, 1, 'pending', false, false, ''),
('Joy', 'Silva', 'bride', '', 'Mount Lavinia', 0, 1, 'pending', false, false, ''),
('Lahiru', 'Peiris', 'bride', '', 'USA', 0, 0, 'pending', false, false, ''),
('Rani', 'Cooray', 'bride', 'Family', 'Moratuwa', 0, 1, 'pending', false, false, ''),
('Sriyan', 'Fernando', 'bride', '', 'Moratuwa', 0, 5, 'pending', false, false, ''),
('Shehan', 'Jayawardena', 'bride', '', 'Wattala', 0, 2, 'pending', false, false, ''),
('Sanath', 'Jayawardena', 'bride', '', 'Wattala', 0, 2, 'pending', false, false, ''),
('Sr. Sharmila', 'Jayawardena', 'bride', '', 'Wattala', 0, 1, 'pending', false, false, ''),
('Mahendra', 'Ranasuriya', 'bride', '', 'Canada', 0, 0, 'pending', false, false, ''),
('Ruwan', 'Wanigasekara', 'bride', '', 'Canada', 0, 0, 'pending', false, false, ''),
('Shalendra', 'Ranasuriya', 'bride', '', 'Canada', 0, 0, 'pending', false, false, ''),
('Harendra', 'Fernando', 'bride', '', 'USA', 0, 0, 'pending', false, false, ''),
('Arith', 'Rathnavibhushana', 'bride', '', 'Australia', 0, 0, 'pending', false, false, ''),
('Rajeev', 'Cooray', 'bride', '', 'IDK where he is', 0, 0, 'pending', false, false, ''),
('Erandhi', 'IDK', 'bride', '', 'USA', 0, 0, 'pending', false, false, ''),
('Thushara', 'Perera', 'bride', '', 'Kalutara', 0, 3, 'pending', false, false, ''),
('Shandala', 'Jayawardene', 'bride', '', 'Australia', 0, 0, 'pending', false, false, ''),
('Gampaha', '', 'bride', '', 'Gampaha', 0, 6, 'pending', false, false, ''),
('Anoja', 'Fernando', 'bride', '', 'Panadura', 0, 1, 'pending', false, false, ''),
('Ramani', 'Soysa', 'bride', '', 'Moratuwa', 0, 1, 'pending', false, false, ''),
('Nilmini', 'Silva', 'bride', '', 'Kohuwala', 0, 1, 'pending', false, false, ''),
('Suranjika', 'Bartholomeusz', 'bride', '', 'Dehiwala', 0, 1, 'pending', false, false, ''),
('Rapti', 'Fernando', 'bride', '', 'Thalawathugoda', 0, 1, 'pending', false, false, ''),
('Preethi', 'Jayawardena', 'bride', '', 'Kotte', 0, 4, 'pending', false, false, ''),
('Dimuthu', 'Fernando', 'bride', '', 'Moratuwa', 0, 3, 'pending', false, false, ''),
('Chaminda', 'Perera', 'bride', '', 'Ratmalana', 0, 3, 'pending', false, false, ''),
('Priyal', 'Fernando', 'bride', '', 'Moratuwa', 0, 3, 'pending', false, false, ''),
('Suren', 'De Mel', 'bride', '', 'Moratuwa', 0, 2, 'pending', false, false, ''),
('Prasangi', 'Gajanayake', 'bride', '', 'Dehiwala', 0, 2, 'pending', false, false, ''),
('Ruwinya', 'Jayawardena', 'bride', 'Friends', 'Kotte', 0, 0, 'pending', false, false, ''),
('Senali', 'Karunanayake', 'bride', 'Retinue', 'Rajagiriya', 0, 1, 'pending', false, false, ''),
('Nethmi', 'De Silva', 'bride', 'Retinue', 'Moratuwa', 0, 1, 'pending', false, false, ''),
('Dulmi', 'De Alwis', 'bride', 'Retinue', 'Moratuwa', 0, 1, 'pending', false, false, ''),
('Shehana', 'Liyanage', 'bride', 'Retinue', 'Moratuwa', 0, 1, 'pending', false, false, ''),
('Vihanya', 'Mendis', 'bride', 'Retinue', 'Moratuwa', 0, 1, 'pending', false, false, ''),
('Yalindi', 'Amarasinghe', 'bride', '', 'Maharagama', 0, 0, 'pending', false, false, ''),
('Jina', 'Hapuarachchi', 'bride', 'Retinue', 'Panadura', 0, 2, 'pending', false, false, ''),
('Savidu', 'Cooray', 'bride', 'Retinue', 'Moratuwa', 0, 1, 'pending', false, false, ''),
('Venoji', 'Weerawardena', 'bride', 'Retinue', 'Moratuwa', 0, 2, 'pending', false, false, ''),
('Nethsarani', 'Weerarathne', 'bride', 'Retinue', 'Mount Lavinia', 0, 2, 'pending', false, false, ''),
('Shalindie', 'Punchihewa', 'bride', 'Retinue', 'Panadura', 0, 1, 'pending', false, false, ''),
('Drama', 'Class', 'bride', 'Students', '', 0, 4, 'pending', false, false, ''),
('Suranji Aunty', '', 'bride', 'Relations', 'Moratuwa', 0, 1, 'pending', false, false, ''),
('Malla Friends', '', 'bride', 'Friends', 'Moratuwa', 0, 5, 'pending', false, false, ''),
('Vinesha', '', 'bride', '', '', 0, 0, 'pending', false, false, ''),
('Thanusha', '', 'bride', '', 'Moratuwa', 0, 1, 'pending', false, false, ''),
('Heshan Office', '', 'bride', 'Office', '', 0, 0, 'pending', false, false, ''),
('Mahesha', 'Perera', 'bride', '', '', 0, 2, 'pending', false, false, ''),
('Shenika', '', 'bride', 'Retinue', '', 0, 2, 'pending', false, false, ''),
('Dilakshi Miss', '', 'bride', '', 'Australia', 0, 2, 'pending', false, false, ''),
('Tharika', '', 'bride', 'Retinue', '', 0, 1, 'pending', false, false, ''),
('Hashmarine', '', 'bride', 'Retinue', '', 0, 1, 'pending', false, false, ''),
('Neil Bakery', '', 'bride', '', '', 0, 2, 'pending', false, false, ''),
('Amayas Students', '', 'bride', 'Students', '', 0, 0, 'pending', false, false, ''),
('Viranthi', '', 'bride', '', '', 0, 1, 'pending', false, false, ''),
('Asanka', '', 'bride', '', '', 0, 2, 'pending', false, false, '');

-- ============================================================
-- Seed Data — Shavin's Guest List (Groom's Side)
-- ============================================================

INSERT INTO guest_items (first_name, last_name, side, category, address, gifted_amount, count, rsvp_status, save_the_date_sent, invitation_sent, meal_preference) VALUES
('Nithila', 'Mendis', 'groom', 'School', 'Willorawatte, Moratuwa', 0, 1, 'pending', false, false, ''),
('Sudeera', 'Fernando', 'groom', 'School', 'Koralawella, Moratuwa', 0, 1, 'pending', false, false, ''),
('Chamod', 'Randika', 'groom', 'School', 'Old galle road, Moratuwa', 0, 1, 'pending', false, false, ''),
('Jehan', 'Gomes', 'groom', 'School', 'Old galle road, Moratuwa', 0, 1, 'pending', false, false, ''),
('Ashen', 'Vidusha', 'groom', 'School', 'Old galle road, Moratuwa', 0, 1, 'pending', false, false, ''),
('Nadun', 'Alahakoon', 'groom', 'School', 'Old galle road, Moratuwa', 0, 1, 'pending', false, false, ''),
('Lakshan', 'Wijewickrama', 'groom', 'School', 'Dubai', 0, 0, 'pending', false, false, ''),
('Sandaru', 'Dias', 'groom', 'School', 'Lakshapathiya, Moratuwa', 0, 1, 'pending', false, false, ''),
('Aaran', '', 'groom', 'School', 'USA', 0, 0, 'pending', false, false, ''),
('Shenol', 'Fernando', 'groom', 'School', 'Australia', 0, 0, 'pending', false, false, ''),
('Sahan', 'Shamendra', 'groom', 'School', 'Uyana, Moratuwa', 0, 1, 'pending', false, false, ''),
('Pamuditha', 'Jayasiri', 'groom', 'Uni', 'Kegalle', 0, 1, 'pending', false, false, ''),
('Chirath', 'Sirimanna', 'groom', 'Uni', 'Nugegoda', 0, 1, 'pending', false, false, ''),
('Nandun', 'Dias', 'groom', 'Uni', 'Hikkaduwa', 0, 1, 'pending', false, false, ''),
('Kithmin', 'Pathirana', 'groom', 'Uni', '', 0, 1, 'pending', false, false, ''),
('Dinuka', 'Walpola', 'groom', 'Uni', 'Weliweriya', 0, 1, 'pending', false, false, ''),
('Dinura', 'Samarajeewa', 'groom', 'Uni', 'Mount Lavinia', 0, 1, 'pending', false, false, ''),
('Isuru', 'Attanayake', 'groom', 'Uni', 'Mahiyanganaya', 0, 1, 'pending', false, false, ''),
('Isuru', 'Kumarasinghe', 'groom', 'Office', 'Kandy', 0, 1, 'pending', false, false, ''),
('Kasun', 'Bandara', 'groom', 'Office', 'Kandy', 0, 1, 'pending', false, false, ''),
('Tharanga', 'Priyamal', 'groom', 'Office', 'Awissawella', 0, 1, 'pending', false, false, ''),
('Yehen', 'Tennakoon', 'groom', 'Office', 'Mount Lavinia', 0, 1, 'pending', false, false, ''),
('Janith', 'Harinda', 'groom', 'Office', 'Matara', 0, 1, 'pending', false, false, ''),
('Kaveesha', 'Jayamaha', 'groom', 'Office', 'Kandana', 0, 1, 'pending', false, false, ''),
('Lakshan', 'Costa', 'groom', 'Office', 'Ja-Ela', 0, 1, 'pending', false, false, ''),
('Tharuprabha', 'Perera', 'groom', 'Office', 'Moratuwa', 0, 1, 'pending', false, false, ''),
('Gawsan', 'Raveenthiran', 'groom', 'Uni', 'Batticaloa', 0, 0, 'pending', false, false, ''),
('Nuwan', 'Wickramasingha', 'groom', 'Uni', 'Awissawella', 0, 0, 'pending', false, false, ''),
('Oshadha', 'Punchihewa', 'groom', 'Uni', 'Matara', 0, 0, 'pending', false, false, ''),
('Tharushika', 'Senarathna', 'groom', 'Uni', '', 0, 0, 'pending', false, false, ''),
('Vidath', 'Amarasekara', 'groom', 'Office', 'Ragama', 0, 1, 'pending', false, false, ''),
('Masheesh', 'Ikram', 'groom', 'Office', 'Colombo', 0, 1, 'pending', false, false, ''),
('Tharindu', 'Gamlath', 'groom', 'Office', '', 0, 1, 'pending', false, false, ''),
('Inaam', 'Mahmoor', 'groom', 'Office', 'Colombo', 0, 1, 'pending', false, false, ''),
('Heshan', 'Gunasekara', 'groom', 'Office', '', 0, 1, 'pending', false, false, ''),
('Lalinda', 'Adihetti', 'groom', 'Office', 'Mount Lavinia', 0, 1, 'pending', false, false, ''),
('Sujith', 'Wijerathna', 'groom', 'Office', '', 0, 1, 'pending', false, false, ''),
('Romario', 'Joseph', 'groom', 'Relations', 'Ragama', 0, 1, 'pending', false, false, ''),
('Nethmi', 'Wijesinghe', 'groom', '', 'Australia', 0, 1, 'pending', false, false, ''),
('Sanjeeva', 'Silva', 'groom', '', 'UK', 0, 2, 'pending', false, false, ''),
('Eshan & Family', '', 'groom', 'Family', '', 0, 6, 'pending', false, false, ''),
('Nishantha & Family', '', 'groom', 'Family', '', 0, 3, 'pending', false, false, ''),
('Lalith Fonseka', '', 'groom', 'Family', '', 0, 2, 'pending', false, false, ''),
('Lashendra & Family', '', 'groom', 'Family', '', 0, 0, 'pending', false, false, ''),
('Eshan''s friends', '', 'groom', 'Friends', '', 0, 6, 'pending', false, false, ''),
('Thamma', '', 'groom', 'Family', '', 0, 1, 'pending', false, false, ''),
('Shanka & Family', '', 'groom', 'Family', '', 0, 3, 'pending', false, false, ''),
('Amal & Family', '', 'groom', 'Family', '', 0, 4, 'pending', false, false, ''),
('Dulakshi & husband', '', 'groom', 'Family', '', 0, 2, 'pending', false, false, ''),
('Arosh & Family', '', 'groom', 'Family', '', 0, 4, 'pending', false, false, ''),
('Ajith & Family', '', 'groom', 'Family', '', 0, 3, 'pending', false, false, ''),
('Lavanya friends', '', 'groom', 'Friends', '', 0, 3, 'pending', false, false, ''),
('Chandral & wife', '', 'groom', 'Family', '', 0, 2, 'pending', false, false, ''),
('Seeyas family', '', 'groom', 'Family', '', 0, 6, 'pending', false, false, '');
